# These are supported funding model platforms

github: aasumitro # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
community_bridge: SITGMIM # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: ["https://www.paypal.me/aasumitro", aasumitro.id] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
